c_admin/brand/urls.py
from django.conf.urls import patterns, url
from .views import BrandList, BrandEdit, BrandAdd, BrandDel


urlpatterns = patterns('',
                       url(r'^$', BrandList.as_view(), {}, 'brand'),
                       url(r'^edit/(?P<pk>[0-9]+)/', BrandEdit.as_view(), {}, 'brand_edit'),
                       url(r'^del/(?P<pk>[0-9]+)/', BrandDel.as_view(), {}, 'brand_del'),
                       url(r'^add/', BrandAdd.as_view(), {}, 'brand_add'),
)

c_admin/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.views import login, logout


urlpatterns = patterns('',
                       url(r'^$', include('c_admin.membrane.urls')),
                       url(r'^membrane/', include('c_admin.membrane.urls')),
                       url(r'^membrane_category/', include('c_admin.membrane_category.urls')),
                       url(r'^brand/', include('c_admin.brand.urls')),
                       url(r'^solution/', include('c_admin.solution.urls')),
                       url(r'^object/', include('c_admin.object.urls')),
                       url(r'^accessory/', include('c_admin.accessory.urls')),
                       url(r'^article/', include('c_admin.article.urls')),
                       url(r'^document/', include('c_admin.document.urls')),
                       url(r'^document_group/', include('c_admin.document_group.urls')),
                       url(r'^video/', include('c_admin.video.urls')),
                       url(r'^login/$', login, {'template_name': 'c_admin/login.html'}, 'login'),
                       url(r'^logout/$', logout),
)

membrane/urls.py
from django.conf.urls import patterns, url
from .views import MembraneDetail, CategoryDetail, BrandDetail


urlpatterns = patterns('',
                       url(r'^category/(?P<slug>[-_\w]+)/', CategoryDetail.as_view(), {}, 'category'),
                       url(r'^brand/(?P<slug>[-_\w]+)/', BrandDetail.as_view(), {}, 'brand'),
                       url(r'^(?P<slug>[-_\w]+)/', MembraneDetail.as_view(), {}, 'membrane'),
                       )

urls/urls.py
from django.views.generic.base import TemplateView
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from index.views import Index, ContactForm
import debug_toolbar



urlpatterns = [
    url(r'^$', Index.as_view(), {}, 'index'),
    url(r'^membrane/', include('membrane.urls')),
    url(r'^solution/', include('solution.urls')),
    url(r'^accessory/', include('accessory.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^object/', include('object.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^doc/', include('document.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^c_admin/', include('c_admin.urls')),
    url(r'^carousel/', include('carousel.urls')),
    url(r'^s/', TemplateView.as_view(template_name='google.html')),
    url(r'^contacts/', TemplateView.as_view(template_name='contacts.html')),
    url(r'^contacts_post/', ContactForm.as_view()),
    url(r'^about/', TemplateView.as_view(template_name='about.html')),
    url(r'^mission/', TemplateView.as_view(template_name='mission.html')),
    url(r'^production/', TemplateView.as_view(template_name='production.html')),
    url(r'^trainings/', TemplateView.as_view(template_name='trainings.html')),
    url(r'^partners/', TemplateView.as_view(template_name='partners.html')),
    url(r'^solution-calc/', TemplateView.as_view(template_name='solution-calc.html')),
    url(r'^solution-choice/', TemplateView.as_view(template_name='solution-choice.html')),
    url(r'^404/', TemplateView.as_view(template_name='404.html')),
    url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^__debug__/', include(debug_toolbar.urls)),
]

membrane/models.py
# -*- coding: utf-8 -*-
from django.db import models
from precise_bbcode.fields import BBCodeTextField


class MembraneColors(models.Model):
    color_name = models.CharField(u'Название', max_length=255)
    color_hex = models.CharField(u'Цвет в HEX', max_length=255)

    def __unicode__(self):
        return self.color_name


class MembranePack(models.Model):
    thick = models.FloatField(u'Толщина мембраны, мм', )
    w = models.FloatField(u'Ширина рулона, м', )
    l = models.IntegerField(u'Длина рулона, м', )
    rols = models.IntegerField(u'Кол-во рулонов на палете', )

    def __unicode__(self):
        return u'%s; %s; %s; %s' % (self.thick, self.w, self.l, self.rols)


class MembraneCategory(models.Model):
    title = models.CharField(u'Тип гидроизяляции', max_length=255)
    title_meta = models.CharField(u'Значение тега <metatitle>', max_length=255)
    slug = models.SlugField(u'URL', blank=True)
    order = models.IntegerField(u'Порядок сортировки')
    desc = models.TextField(u'Краткий текст описания в Hero', )
    desc_ext = models.TextField(u'Краткий текст описания на Главную', blank=True)
    info = models.TextField(u'Описание в тело страницы', blank=True)
    img_p = models.ImageField(u'Изображение превью', upload_to='membrane', blank=True)
    img_p_title = models.CharField(u'Title-атрибут изображения превью', max_length=255, blank=True)
    img_p_alt = models.CharField(u'Alt-атрибут изображения', max_length=255, blank=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['order']


class MembraneAdv(models.Model):
    title = models.CharField(u'Преимущество', max_length=255)

    def __unicode__(self):
        return self.title


class MembraneReinforce(models.Model):
    title = models.CharField(u'Преимущество', max_length=255)

    def __unicode__(self):
        return self.title


class MembrBrandAdv(models.Model):
    ico = models.ImageField(u'Изображение', upload_to='brand', blank=True)
    title = models.CharField(u'Текст преимущества', max_length=255)

    def __unicode__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField(u'Название', max_length=255)
    title_meta = models.CharField(u'Значение тега <metatitle>', max_length=255)
    slug = models.SlugField(u'URL', blank=True)
    order = models.IntegerField(u'Порядок сортировки')
    hero = models.CharField(u'Hero', max_length=255, blank=True)
    img_p = models.ImageField(u'Изображение превью', upload_to='brand', blank=True)
    img_p_title = models.CharField(u'Title-атрибут изображения превью', max_length=255, blank=True)
    img_p_alt = models.CharField(u'Alt-атрибут изображения', max_length=255, blank=True)
    img_main = models.ImageField(u'Главное изображение', upload_to='brand', blank=True)
    img_main_title = models.CharField(u'Title-атрибут изображения превью', max_length=255, blank=True)
    img_main_alt = models.CharField(u'Alt-атрибут изображения', max_length=255, blank=True)
    img_logo = models.ImageField(u'Изображение логотипа', upload_to='brand', blank=True)
    img_logo_title = models.CharField(u'Title-атрибут изображения', max_length=255, blank=True)
    img_logo_alt = models.CharField(u'Alt-атрибут изображения', max_length=255, blank=True)
    definition = models.CharField(u'Краткий текст определения бренда', max_length=255)
    desc = models.CharField(u'Краткий текст описания бренда', max_length=255)
    info = models.TextField(u'Описание в тело страницы', blank=True)
    adv = models.ManyToManyField(MembrBrandAdv, verbose_name=u'Преимущества')
    add = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['order']


class Membrane(models.Model):
    POLYMER_TYPE = (
        ('pvh', u'ПВХ'),
        ('tpo', u'ТПО'),
    )
    title = models.CharField(u'Название', max_length=255)
    title_meta = models.CharField(u'Значение тега <metatitle>', max_length=255)
    slug = models.SlugField(u'URL', blank=True)
    order = models.IntegerField(u'Порядок сортировки')
    img_p = models.ImageField(u'Изображение превью', upload_to='membrane', blank=True)
    img_p_title = models.CharField(u'Title-атрибут', max_length=255, blank=True)
    img_p_alt = models.CharField(u'Alt-атрибут', max_length=255, blank=True)
    img_main = models.ImageField(u'Главное изображение', upload_to='membrane', blank=True)
    img_main_title = models.CharField(u'Title-атрибут', max_length=255, blank=True)
    img_main_alt = models.CharField(u'Alt-атрибут', max_length=255, blank=True)
    desc = models.TextField(u'Краткий текст описания', )
    target = BBCodeTextField(u'Назначение', )
    adv = models.ManyToManyField(MembraneAdv, verbose_name=u'Текстовое описание преимуществ')
    polymer = models.CharField(u'Тип полимера', choices=POLYMER_TYPE, max_length=16)
    reinforce = models.ManyToManyField(MembraneReinforce, verbose_name=u'Типы армирования')
    colors = models.ManyToManyField(MembraneColors, verbose_name=u'Цвет')
    pack_text = models.TextField(u'Описание упаковки', blank=True)
    pack = models.ManyToManyField(MembranePack, verbose_name=u'Характеристики упаковки', blank=True)
    store = BBCodeTextField(u'Условия хранения', blank=True)
    brand = models.ForeignKey(Brand, verbose_name=u'Бренд мембраны')
    category = models.ForeignKey(MembraneCategory, verbose_name=u'Тип гидроизоляции')
    thickness = models.CharField(u'Толщина, мм', max_length=255)
    strength = models.IntegerField(u'Прочность, Мпа, вдоль рулона', blank=True, null=True)
    strengthp = models.IntegerField(u'Прочность, Мпа, поперек рулона', blank=True, null=True)
    elongation = models.IntegerField(u'Относительное удлинение, %', blank=True, null=True)
    absorp = models.FloatField(u'Водопоглащение, %', blank=True, null=True)
    flex = models.IntegerField(u'Гибкость', blank=True, null=True)
    resist = models.CharField(u'Сопротивление статическому продавливанию', max_length=255, blank=True)
    comb = models.CharField(u'Группа горючести', max_length=255, blank=True)
    add = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['order']

c_admin/accessory/forms.py
from accessory.models import Accessory
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = Accessory
        fields = ('title', 'title_meta', 'slug', 'order', 'img_main', 'img_main_title', 'img_main_alt', 'img_p',
                  'img_p_title', 'img_p_alt', 'desc', 'body', 'membrane', 'solution', 'subcategory')
        widgets = {'img_main_ext': ImageWidget(), 'img_main': ImageWidget()}

c_admin/article/forms.py
from article.models import Article
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = Article
        fields = ('title', 'title_meta', 'slug', 'add', 'img_main', 'img_main_title', 'img_main_alt',  'type', 'desc', 'body',
                  'membrane', 'solution', 'accessory')
        widgets = {'img_main_ext': ImageWidget(), 'img_main': ImageWidget()}

c_admin/document/forms.py
from document.models import Document
from ..utils.forms import BaseModelForm


class EditAddForm(BaseModelForm):
    class Meta:
        model = Document
        fields = ('title', 'order', 'country', 'pdf', 'doc', 'dwg',  'ppt', 'category', 'type',
                  'membrane', 'solution', 'accessory')

c_admin/accessory/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from accessory.models import Accessory
from .forms import EditAddForm


class AccessoryList(ListView):
    template_name = 'c_admin/accessory/index.html'
    context_object_name = "accessorys"
    model = Accessory


class AccessoryDel(DeleteView):
    model = Accessory
    template_name = 'c_admin/accessory/del.html'
    success_url = '/c_admin/accessory/'


class AccessoryEdit(UpdateView):
    form_class = EditAddForm
    model = Accessory
    template_name = 'c_admin/accessory/edit.html'
    success_url = '/c_admin/accessory/'


class AccessoryAdd(CreateView):
    form_class = EditAddForm
    model = Accessory
    template_name = 'c_admin/accessory/edit.html'
    success_url = '/c_admin/accessory/'

c_admin/article/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from article.models import Article
from .forms import EditAddForm


class ArticleList(ListView):
    template_name = 'c_admin/article/index.html'
    context_object_name = "articles"
    model = Article


class ArticleDel(DeleteView):
    model = Article
    template_name = 'c_admin/article/del.html'
    success_url = '/c_admin/article/'


class ArticleEdit(UpdateView):
    form_class = EditAddForm
    model = Article
    template_name = 'c_admin/article/edit.html'
    success_url = '/c_admin/article/'


class ArticleAdd(CreateView):
    form_class = EditAddForm
    model = Article
    template_name = 'c_admin/article/edit.html'
    success_url = '/c_admin/article/'

c_admin/brand/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from membrane.models import Brand
from .forms import EditAddForm


class BrandList(ListView):
    template_name = 'c_admin/brand/index.html'
    context_object_name = "brands"
    model = Brand


class BrandDel(DeleteView):
    model = Brand
    template_name = 'c_admin/brand/del.html'
    success_url = '/c_admin/brand/'


class BrandEdit(UpdateView):
    form_class = EditAddForm
    model = Brand
    template_name = 'c_admin/brand/edit.html'
    success_url = '/c_admin/brand/'


class BrandAdd(CreateView):
    form_class = EditAddForm
    model = Brand
    template_name = 'c_admin/brand/edit.html'
    success_url = '/c_admin/brand/'

c_admin/document/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from document.models import Document
from .forms import EditAddForm


class DocumentList(ListView):
    template_name = 'c_admin/document/index.html'
    context_object_name = "documents"
    model = Document


class DocumentDel(DeleteView):
    model = Document
    template_name = 'c_admin/document/del.html'
    success_url = '/c_admin/document/'


class DocumentEdit(UpdateView):
    form_class = EditAddForm
    model = Document
    template_name = 'c_admin/document/edit.html'
    success_url = '/c_admin/document/'


class DocumentAdd(CreateView):
    form_class = EditAddForm
    model = Document
    template_name = 'c_admin/document/edit.html'
    success_url = '/c_admin/document/'

c_admin/document_group/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from document.models import DocumentGroup
from .forms import EditAddForm


class DocumentGroupList(ListView):
    template_name = 'c_admin/document_group/index.html'
    context_object_name = "document_groups"
    model = DocumentGroup


class DocumentGroupDel(DeleteView):
    model = DocumentGroup
    template_name = 'c_admin/document_group/del.html'
    success_url = '/c_admin/document_group/'


class DocumentGroupEdit(UpdateView):
    form_class = EditAddForm
    model = DocumentGroup
    template_name = 'c_admin/document_group/edit.html'
    success_url = '/c_admin/document_group/'


class DocumentGroupAdd(CreateView):
    form_class = EditAddForm
    model = DocumentGroup
    template_name = 'c_admin/document_group/edit.html'
    success_url = '/c_admin/document_group/'

c_admin/membrane/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from membrane.models import Membrane
from .forms import EditAddForm


class MembraneList(ListView):
    template_name = 'c_admin/membrane/index.html'
    context_object_name = "membranes"
    model = Membrane


class MembraneDel(DeleteView):
    model = Membrane
    template_name = 'c_admin/membrane/del.html'
    success_url = '/c_admin/membrane/'


class MembraneEdit(UpdateView):
    form_class = EditAddForm
    model = Membrane
    template_name = 'c_admin/membrane/edit.html'
    success_url = '/c_admin/membrane/'


class MembraneAdd(CreateView):
    form_class = EditAddForm
    model = Membrane
    template_name = 'c_admin/membrane/edit.html'
    success_url = '/c_admin/membrane/'

c_admin/membrane_category/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView

from membrane.models import MembraneCategory
from .forms import EditAddForm


class MembraneCategoryList(ListView):
    template_name = 'c_admin/membrane_category/index.html'
    context_object_name = "membrane_category"
    model = MembraneCategory


class MembraneCategoryEdit(UpdateView):
    form_class = EditAddForm
    model = MembraneCategory
    template_name = 'c_admin/membrane_category/edit.html'
    success_url = '/c_admin/membrane_category/'


class MembraneCategoryAdd(CreateView):
    form_class = EditAddForm
    model = MembraneCategory
    template_name = 'c_admin/membrane_category/edit.html'
    success_url = '/c_admin/membrane_category/'

c_admin/object/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from object.models import Object
from .forms import EditAddForm


class ObjectList(ListView):
    template_name = 'c_admin/object/index.html'
    context_object_name = "objects"
    model = Object


class ObjectDel(DeleteView):
    model = Object
    template_name = 'c_admin/object/del.html'
    success_url = '/c_admin/object/'


class ObjectEdit(UpdateView):
    form_class = EditAddForm
    model = Object
    template_name = 'c_admin/object/edit.html'
    success_url = '/c_admin/object/'


class ObjectAdd(CreateView):
    form_class = EditAddForm
    model = Object
    template_name = 'c_admin/object/edit.html'
    success_url = '/c_admin/object/'

c_admin/templates/c_admin/membrane/del.html
{% extends "c_admin/base.html" %}
{% block css %}
{% endblock %}
{% block js %}
{% endblock %}
{% block title %}Удаление мембраны{% endblock %}
{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        Удаление нельзя отменить
    </div>
    <div class="panel-body text-center">


        <h3>{{ membr.title }}</h3>

        <form action="" method="post">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger">Удалить</button>
            <a href="/c_admin/membrane/" class="btn btn-success btn-lg">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

c_admin/templates/c_admin/membrane/edit.html
{% extends "c_admin/base.html" %}
{% block css %}
  <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet"/>
  <link href="/static/c_admin/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet"/>
{% endblock %}
{% block js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
  <script src="/static/c_admin/bootstrap-fileinput/js/fileinput.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $("#id_polymer, #id_brand, #id_category, #id_pack, #id_colors, #id_adv,#id_reinforce").select2({ width: '100%' });
      $("#id_img_p").fileinput({
        //{#                maxFileSize: 1500,#}
        showClose: false,
        showCaption: false,
        browseLabel: '',
        removeLabel: '',
        browseIcon: '<i class="glyphicon glyphicon-folder-open"></i>',
        removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
        removeTitle: 'Cancel or reset changes',
        msgErrorClass: 'alert alert-block alert-danger',
        defaultPreviewContent: '<img style="width:auto;max-height:500px;" src="' + img_p + '">',
        layoutTemplates: {main2: '{preview} {remove} {browse}'},
        allowedFileExtensions: ["jpg", "jpeg", "png", "gif"]
      });
      $("#id_img_main").fileinput({
        //{#                maxFileSize: 1500,#}
        showClose: false,
        showCaption: false,
        browseLabel: '',
        removeLabel: '',
        browseIcon: '<i class="glyphicon glyphicon-folder-open"></i>',
        removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
        removeTitle: 'Cancel or reset changes',
        msgErrorClass: 'alert alert-block alert-danger',
        defaultPreviewContent: '<img style="width:auto;max-height:500px;" src="' + img_main + '">',
        layoutTemplates: {main2: '{preview} {remove} {browse}'},
        allowedFileExtensions: ["jpg", "jpeg", "png", "gif"]
      });
    });
  </script>
  <script src="/static/ckeditor/ckeditor.js"></script>
  <script>
    CKEDITOR.replace( 'target', {
      customConfig: '/static/ckeditor/config.js'
    });
  </script>
{% endblock %}
{% block title %}Редактирование мембраны{% endblock %}
{% block content %}
  <div class="row">
    <form role="form" action="{{ request.path }}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="form-group">
            {#                        {% include "c_admin/form.html" %}#}
            {{ form.as_div }}
          </div>
        </div>
      </div>
      <div class="col-lg-12 text-center">
        <button type="submit" class="btn btn-outline btn-success btn-lg">Сохранить</button>
        <a href="/c_admin/membrane/" class="btn btn-outline btn-danger btn-lg">Отмена</a>
      </div>
    </form>
  </div>
{% endblock %}

c_admin/templates/c_admin/membrane/index.html
{% extends "c_admin/base.html" %}
{% block css %}
  <link href="/static/c_admin/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">
  <link href="/static/c_admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css"
        rel="stylesheet">
  <link href="/static/c_admin/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
{% endblock %}
{% block js %}
  <script src="/static/c_admin/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
  <script src="/static/c_admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
{% endblock %}
{% block title %}
  Мембраны
{% endblock %}
{% block content %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <a class="text-center btn btn-primary" href="/c_admin/membrane/add/">Добавить мембрану</a>
    </div>
    <div class="panel-body">
      {% if membranes %}
        <div class="dataTable_wrapper">
          <table class="table table-striped table-bordered table-hover" id="dataTables">
            <thead>
            <tr>
              <th>Название мембраны</th>
              <th>URL</th>
              <th>Бренд мембраны</th>
              <th>Тип гидроизяляции</th>
              <th>Дата добавления</th>
              <th>Редактировать</th>
            </tr>
            </thead>
            <tbody>
            {% for membrane in membranes %}
              <tr class="gradeA">
                <td>{{ membrane.title }}</td>
                <td>{{ membrane.slug }}</td>
                <td>{{ membrane.brand }}</td>
                <td>{{ membrane.category }}</td>
                <td>{{ membrane.add }}</td>

                <td>
                  <a class="fa fa-pencil" href="/c_admin/membrane/edit/{{ membrane.id }}/"></a>
                  <a class="fa fa-times" href="/c_admin/membrane/del/{{ membrane.id }}/"></a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <h3></h3>

        <p>Нет мембран или у вас недостаточно прав.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}