c_admin/brand/urls.py
from django.conf.urls import patterns, url
from .views import BrandList, BrandEdit, BrandAdd, BrandDel


urlpatterns = patterns('',
                       url(r'^$', BrandList.as_view(), {}, 'brand'),
                       url(r'^edit/(?P<pk>[0-9]+)/', BrandEdit.as_view(), {}, 'brand_edit'),
                       url(r'^del/(?P<pk>[0-9]+)/', BrandDel.as_view(), {}, 'brand_del'),
                       url(r'^add/', BrandAdd.as_view(), {}, 'brand_add'),
)

c_admin/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.views import login, logout


urlpatterns = patterns('',
                       url(r'^$', include('c_admin.membrane.urls')),
                       url(r'^membrane/', include('c_admin.membrane.urls')),
                       url(r'^membrane_category/', include('c_admin.membrane_category.urls')),
                       url(r'^brand/', include('c_admin.brand.urls')),
                       url(r'^solution/', include('c_admin.solution.urls')),
                       url(r'^object/', include('c_admin.object.urls')),
                       url(r'^accessory/', include('c_admin.accessory.urls')),
                       url(r'^article/', include('c_admin.article.urls')),
                       url(r'^document/', include('c_admin.document.urls')),
                       url(r'^document_group/', include('c_admin.document_group.urls')),
                       url(r'^video/', include('c_admin.video.urls')),
                       url(r'^login/$', login, {'template_name': 'c_admin/login.html'}, 'login'),
                       url(r'^logout/$', logout),
)

urls/urls.py
from django.views.generic.base import TemplateView
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from index.views import Index, ContactForm
import debug_toolbar



urlpatterns = [
    url(r'^$', Index.as_view(), {}, 'index'),
    url(r'^membrane/', include('membrane.urls')),
    url(r'^solution/', include('solution.urls')),
    url(r'^accessory/', include('accessory.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^object/', include('object.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^doc/', include('document.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^c_admin/', include('c_admin.urls')),
    url(r'^carousel/', include('carousel.urls')),
    url(r'^s/', TemplateView.as_view(template_name='google.html')),
    url(r'^contacts/', TemplateView.as_view(template_name='contacts.html')),
    url(r'^contacts_post/', ContactForm.as_view()),
    url(r'^about/', TemplateView.as_view(template_name='about.html')),
    url(r'^mission/', TemplateView.as_view(template_name='mission.html')),
    url(r'^production/', TemplateView.as_view(template_name='production.html')),
    url(r'^trainings/', TemplateView.as_view(template_name='trainings.html')),
    url(r'^partners/', TemplateView.as_view(template_name='partners.html')),
    url(r'^solution-calc/', TemplateView.as_view(template_name='solution-calc.html')),
    url(r'^solution-choice/', TemplateView.as_view(template_name='solution-choice.html')),
    url(r'^404/', TemplateView.as_view(template_name='404.html')),
    url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^__debug__/', include(debug_toolbar.urls)),
]

video/urls.py
from django.conf.urls import url
from .views import VideoList


urlpatterns = [
    url(r'^$', VideoList.as_view(), {}, 'video'),
    url(r'^ll/(?P<o>[0-9]+)/(?P<l>[0-9]+)/$', VideoList.as_view(template_name='video/ll.html'), {},
        'video'),
]

video/models.py
# -*- coding: utf-8 -*-
from django.db import models


class VideoSubject(models.Model):
    title = models.CharField(u'Название', max_length=255)

    def __unicode__(self):
        return self.title


class Video(models.Model):
    title = models.CharField(u'Название', max_length=255)
    desc = models.TextField(u'Базовое описание', blank=True)
    order = models.IntegerField(u'Порядок сортировки')
    subject = models.ForeignKey(VideoSubject, blank=True, null=True)
    url = models.URLField(u'Ссылка на видео')
    add = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['order']

c_admin/accessory/forms.py
from accessory.models import Accessory
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = Accessory
        fields = ('title', 'title_meta', 'slug', 'order', 'img_main', 'img_main_title', 'img_main_alt', 'img_p',
                  'img_p_title', 'img_p_alt', 'desc', 'body', 'membrane', 'solution', 'subcategory')
        widgets = {'img_main_ext': ImageWidget(), 'img_main': ImageWidget()}

c_admin/article/forms.py
from article.models import Article
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = Article
        fields = ('title', 'title_meta', 'slug', 'add', 'img_main', 'img_main_title', 'img_main_alt',  'type', 'desc', 'body',
                  'membrane', 'solution', 'accessory')
        widgets = {'img_main_ext': ImageWidget(), 'img_main': ImageWidget()}

c_admin/brand/forms.py
from membrane.models import Brand
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = Brand
        fields = ('title', 'title_meta', 'slug', 'order', 'hero', 'img_p', 'img_p_title', 'img_p_alt', 'img_main',
                  'img_main_title', 'img_main_alt', 'img_logo', 'img_logo_title', 'img_logo_alt', 'definition', 'desc',
                  'info', 'adv')
        widgets = {'img_p': ImageWidget(), 'img_main': ImageWidget(), 'img_logo': ImageWidget()}

c_admin/document/forms.py
from document.models import Document
from ..utils.forms import BaseModelForm


class EditAddForm(BaseModelForm):
    class Meta:
        model = Document
        fields = ('title', 'order', 'country', 'pdf', 'doc', 'dwg',  'ppt', 'category', 'type',
                  'membrane', 'solution', 'accessory')

c_admin/document_group/forms.py
from document.models import DocumentGroup
from ..utils.forms import BaseModelForm


class EditAddForm(BaseModelForm):
    class Meta:
        model = DocumentGroup
        fields = ('title', 'order', 'fire', 'conf', 'mail')

c_admin/membrane/forms.py
from membrane.models import Membrane
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = Membrane
        fields = ('title', 'slug', 'order', 'img_p', 'img_p_title', 'img_p_alt', 'img_main', 'img_main_title', 'img_main_alt',
                  'desc', 'target', 'adv', 'polymer', 'reinforce', 'colors', 'pack_text', 'pack', 'store',
                  'brand', 'category', 'thickness', 'strength', 'strengthp', 'elongation', 'absorp', 'flex', 'resist',
                  'comb')
        widgets = {'img_p': ImageWidget(), 'img_main': ImageWidget()}

c_admin/membrane_category/forms.py
from membrane.models import MembraneCategory
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = MembraneCategory
        fields = ('title', 'slug', 'order', 'img_p', 'img_p_title', 'img_p_alt', 'title_meta', 'desc', 'desc_ext', 'info')
        widgets = {'img_p': ImageWidget()}

c_admin/object/forms.py
from object.models import Object, ObjectCity
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    def __init__(self, *args, **kwargs):
        super(EditAddForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Object
        fields = ('title', 'title_meta', 'slug', 'order', 'img_p', 'img_p_title', 'img_p_alt', 'img_main',
                  'img_main_title', 'img_main_alt', 'city', 'year', 'area', 'desc', 'type', 'category', 'solution',
                  'membrane')
        widgets = {'img_p': ImageWidget(), 'img_main': ImageWidget()}

c_admin/solution/forms.py
from solution.models import Solution
from ..utils.forms import BaseModelForm
from ..utils.widgets import ImageWidget


class EditAddForm(BaseModelForm):
    class Meta:
        model = Solution
        fields = ('title', 'title_meta', 'slug', 'order', 'img_p', 'img_p_title', 'img_p_alt', 'img_main', 'img_main_title',
                  'img_main_alt', 'category', 'desc', 'desc_ext', 'body', 'svg', 'membrane', 'adv')
        widgets = {'img_p': ImageWidget(), 'img_main_ext': ImageWidget()}

c_admin/video/forms.py
from video.models import Video
from ..utils.forms import BaseModelForm


class EditAddForm(BaseModelForm):
    class Meta:
        model = Video
        fields = ('title', 'order', 'desc', 'subject', 'url')

c_admin/accessory/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from accessory.models import Accessory
from .forms import EditAddForm


class AccessoryList(ListView):
    template_name = 'c_admin/accessory/index.html'
    context_object_name = "accessorys"
    model = Accessory


class AccessoryDel(DeleteView):
    model = Accessory
    template_name = 'c_admin/accessory/del.html'
    success_url = '/c_admin/accessory/'


class AccessoryEdit(UpdateView):
    form_class = EditAddForm
    model = Accessory
    template_name = 'c_admin/accessory/edit.html'
    success_url = '/c_admin/accessory/'


class AccessoryAdd(CreateView):
    form_class = EditAddForm
    model = Accessory
    template_name = 'c_admin/accessory/edit.html'
    success_url = '/c_admin/accessory/'

c_admin/article/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from article.models import Article
from .forms import EditAddForm


class ArticleList(ListView):
    template_name = 'c_admin/article/index.html'
    context_object_name = "articles"
    model = Article


class ArticleDel(DeleteView):
    model = Article
    template_name = 'c_admin/article/del.html'
    success_url = '/c_admin/article/'


class ArticleEdit(UpdateView):
    form_class = EditAddForm
    model = Article
    template_name = 'c_admin/article/edit.html'
    success_url = '/c_admin/article/'


class ArticleAdd(CreateView):
    form_class = EditAddForm
    model = Article
    template_name = 'c_admin/article/edit.html'
    success_url = '/c_admin/article/'

c_admin/brand/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from membrane.models import Brand
from .forms import EditAddForm


class BrandList(ListView):
    template_name = 'c_admin/brand/index.html'
    context_object_name = "brands"
    model = Brand


class BrandDel(DeleteView):
    model = Brand
    template_name = 'c_admin/brand/del.html'
    success_url = '/c_admin/brand/'


class BrandEdit(UpdateView):
    form_class = EditAddForm
    model = Brand
    template_name = 'c_admin/brand/edit.html'
    success_url = '/c_admin/brand/'


class BrandAdd(CreateView):
    form_class = EditAddForm
    model = Brand
    template_name = 'c_admin/brand/edit.html'
    success_url = '/c_admin/brand/'

c_admin/document/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from document.models import Document
from .forms import EditAddForm


class DocumentList(ListView):
    template_name = 'c_admin/document/index.html'
    context_object_name = "documents"
    model = Document


class DocumentDel(DeleteView):
    model = Document
    template_name = 'c_admin/document/del.html'
    success_url = '/c_admin/document/'


class DocumentEdit(UpdateView):
    form_class = EditAddForm
    model = Document
    template_name = 'c_admin/document/edit.html'
    success_url = '/c_admin/document/'


class DocumentAdd(CreateView):
    form_class = EditAddForm
    model = Document
    template_name = 'c_admin/document/edit.html'
    success_url = '/c_admin/document/'

c_admin/document_group/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from document.models import DocumentGroup
from .forms import EditAddForm


class DocumentGroupList(ListView):
    template_name = 'c_admin/document_group/index.html'
    context_object_name = "document_groups"
    model = DocumentGroup


class DocumentGroupDel(DeleteView):
    model = DocumentGroup
    template_name = 'c_admin/document_group/del.html'
    success_url = '/c_admin/document_group/'


class DocumentGroupEdit(UpdateView):
    form_class = EditAddForm
    model = DocumentGroup
    template_name = 'c_admin/document_group/edit.html'
    success_url = '/c_admin/document_group/'


class DocumentGroupAdd(CreateView):
    form_class = EditAddForm
    model = DocumentGroup
    template_name = 'c_admin/document_group/edit.html'
    success_url = '/c_admin/document_group/'

c_admin/membrane/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from membrane.models import Membrane
from .forms import EditAddForm


class MembraneList(ListView):
    template_name = 'c_admin/membrane/index.html'
    context_object_name = "membranes"
    model = Membrane


class MembraneDel(DeleteView):
    model = Membrane
    template_name = 'c_admin/membrane/del.html'
    success_url = '/c_admin/membrane/'


class MembraneEdit(UpdateView):
    form_class = EditAddForm
    model = Membrane
    template_name = 'c_admin/membrane/edit.html'
    success_url = '/c_admin/membrane/'


class MembraneAdd(CreateView):
    form_class = EditAddForm
    model = Membrane
    template_name = 'c_admin/membrane/edit.html'
    success_url = '/c_admin/membrane/'

c_admin/membrane_category/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView

from membrane.models import MembraneCategory
from .forms import EditAddForm


class MembraneCategoryList(ListView):
    template_name = 'c_admin/membrane_category/index.html'
    context_object_name = "membrane_category"
    model = MembraneCategory


class MembraneCategoryEdit(UpdateView):
    form_class = EditAddForm
    model = MembraneCategory
    template_name = 'c_admin/membrane_category/edit.html'
    success_url = '/c_admin/membrane_category/'


class MembraneCategoryAdd(CreateView):
    form_class = EditAddForm
    model = MembraneCategory
    template_name = 'c_admin/membrane_category/edit.html'
    success_url = '/c_admin/membrane_category/'

c_admin/object/views.py
# - coding: utf-8
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from object.models import Object
from .forms import EditAddForm


class ObjectList(ListView):
    template_name = 'c_admin/object/index.html'
    context_object_name = "objects"
    model = Object


class ObjectDel(DeleteView):
    model = Object
    template_name = 'c_admin/object/del.html'
    success_url = '/c_admin/object/'


class ObjectEdit(UpdateView):
    form_class = EditAddForm
    model = Object
    template_name = 'c_admin/object/edit.html'
    success_url = '/c_admin/object/'


class ObjectAdd(CreateView):
    form_class = EditAddForm
    model = Object
    template_name = 'c_admin/object/edit.html'
    success_url = '/c_admin/object/'

c_admin/templates/c_admin/video/del.html
{% extends "c_admin/base.html" %}
{% block title %}Удаление видео{% endblock %}
{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        Удаление нельзя отменить
    </div>
    <div class="panel-body text-center">
        <h3>{{ document.title }}</h3>

        <form action="" method="post">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger">Удалить</button>
            <a href="/c_admin/video/" class="btn btn-success btn-lg">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

c_admin/templates/c_admin/video/edit.html
{% extends "c_admin/base.html" %}
{% block css %}
  <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet"/>
{% endblock %}
{% block js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $("#id_subject").select2({ width: '100%' });
    });
  </script>
{% endblock %}
{% block title %}Редактирование видео{% endblock %}
{% block content %}
  <div class="row">
    <form role="form" action="{{ request.path }}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="form-group">
            {{ form.as_div }}
          </div>
        </div>
      </div>
      <div class="col-lg-12 text-center">
        <button type="submit" class="btn btn-outline btn-success btn-lg">Сохранить</button>
        <a href="/c_admin/video/" class="btn btn-outline btn-danger btn-lg">Отмена</a>
      </div>
    </form>
  </div>
{% endblock %}

c_admin/templates/c_admin/video/index.html
{% extends "c_admin/base.html" %}
{% block css %}
  <link href="/static/c_admin/bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">
  <link href="/static/c_admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css"
        rel="stylesheet">
  <link href="/static/c_admin/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
{% endblock %}
{% block js %}
  <script src="/static/c_admin/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
  <script src="/static/c_admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
{% endblock %}
{% block title %}Видео{% endblock %}
{% block content %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <a class="text-center btn btn-primary" href="/c_admin/video/add/">Добавить видео</a>
    </div>
    <div class="panel-body">
      {% if videos %}
        <div class="dataTable_wrapper">
          <table class="table table-striped table-bordered table-hover" id="dataTables">
            <thead>
            <tr>
              <th>Заголовок</th>
              <th>URL</th>
              <th>Категория</th>
              <th>Мембраны</th>
              <th>Подкатегория</th>
              <th>Редактировать</th>
            </tr>
            </thead>
            <tbody>
            {% for video in videos %}
              <tr class="gradeA">
                <td>{{ video.title }}</td>
                <td>{{ video.slug }}</td>
                <td>{{ video.category }}</td>
                <td>{{ video.membrane__set.all }}</td>
                <td>{{ video.subcategory }}</td>
                <td>
                  <a class="fa fa-pencil" href="/c_admin/video/edit/{{ video.id }}/"></a>
                  <a class="fa fa-times" href="/c_admin/video/del/{{ video.id }}/"></a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <h3></h3>
        <p>Нет видео или у вас недостаточно прав.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}